# Generated by Django 5.2.8 on 2026-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
